version: '3.7'

services:
  #eureka-server
  eureka-server:
    image: ahmedbaz/eureka-server:1.2.0
    restart: always
    environment:
      EUREKA_CLIENT_FETCH-REGISTRY: "false"
      EUREKA_CLIENT_REGISTER-WITH-EUREKA: "false"
    ports:
      - '8761:8761'