version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - learn-hub-net  

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/datasources
    networks:
      - learn-hub-net  
        
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:2.23
    restart: always
    ports:
      - '9411:9411'      
    networks:
     - learn-hub-net
       
networks:
  learn-hub-net:
    driver: bridge     
  