scrape_configs:
  - job_name: 'learn-hub-metrics'
    metrics_path: 'actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['192.168.0.101:9999']
        labels:
          application: 'learn-hub-service'