version: '3.8'

services:

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    depends_on:
       - keycloak-db
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5333/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    command:
      - "start-dev"
    ports:
      - '9696:8080'
    networks:
      - demo_net

  keycloak-db:
    image: postgres:alpine3.17
    container_name: keycloak-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: 5333
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5333:5333'
    networks:
      - demo_net
    restart: always

volumes:
  postgres_data:
    driver: local

networks:
  demo_net:
    driver: bridge