version: '3.8'

services:

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_PORT: 9696
    command:
      - "start-dev"
    ports:
      - '9696:8080'
    networks:
      - e-commerce-net

networks:
  e-commerce-net:
    driver: bridge