version: '3.8'

services:

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: h2
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/myrealm.json
    command:
      - "start-dev"
    ports:
      - '9696:8080'
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./config:/opt/keycloak/config
    networks:
      - demo-net
      
volumes:
  keycloak-data:

networks:
  demo-net:
    driver: bridge