version: '3.8'

services:

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db:5444
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    command:
      - "start-dev"
    ports:
      - '9696:8080'
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - demo-net

  keycloak-db:
    image: postgres:alpine3.17
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      PGDATA: /var/lib/postgresql/data
      PGPORT: 5444
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5444:5444"
    networks:
      - demo-net
    restart: always

volumes:
  keycloak-data:
    driver: local
  postgres-data:
    driver: local

networks:
  demo-net:
    driver: bridge