services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:latest
    ports:
      - "8081:8080"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks: 
      - jenkins-net 
 
volumes:
    jenkins-log:
    jenkins-data: 

networks: 
    jenkins-net: 