version: '3.8'

services:
  mysql_1:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: employee
    ports:
      - "3306:3306"
  mysql_2:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: employee_app
    ports:
      - "3305:3306"      
