version: '3.8'

services:
  postgres_1:
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "1024:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
  postgres_2:
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "1025:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data   

volumes:
  postgres-data: